apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: openshift-demo-app-v2
  labels:
    app: openshift-demo-app-v2
    version: v2
spec:
  output:
    to:
      kind: ImageStreamTag
      name: openshift-demo-app-v2:latest
  source:
    type: Git
    git:
      uri: https://github.com/greyhoundforty/tech-labs-dallas.git  # Replace with actual repo URL
    contextDir: v2
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: python:3.9-ubi8
      env:
      - name: PIP_INDEX_URL
        value: https://pypi.org/simple/
      - name: UPGRADE_PIP_TO_LATEST
        value: "true"
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChange: {}

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openshift-demo-app-v2
  labels:
    app: openshift-demo-app-v2
    version: v2
