apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: v2-sqlite-pvc
  labels:
    app: openshift-demo-app-v2
    version: v2
    storage-type: sqlite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2  # Change to your cluster's default storage class if different

---
# Optional: ConfigMap for SQLite configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: v2-sqlite-config
  labels:
    app: openshift-demo-app-v2
    version: v2
data:
  # SQLite configuration settings
  sqlite_path: "/app/data/v2_demo.db"
  sqlite_timeout: "30"
  sqlite_journal_mode: "WAL"
  database_info: |
    This PVC provides persistent storage for the SQLite database.
    Data will survive pod restarts, scaling events, and node failures.
    Perfect for demonstrating persistent storage concepts in OpenShift!