apiVersion: v1
kind: Namespace
metadata:
  name: secrets-manager-csi-driver
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: secrets-manager-csi-driver-scc
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities:
- SYS_ADMIN
defaultAddCapabilities: []
fsGroup:
  type: RunAsAny
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:secrets-manager-csi-driver:secrets-manager-csi-driver
volumes:
- hostPath
- secret
- configMap
- emptyDir
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: secrets-manager-csi-driver
  name: secrets-manager-csi-driver
  namespace: secrets-manager-csi-driver
spec:
  selector:
    matchLabels:
      app: secrets-manager-csi-driver
  template:
    metadata:
      labels:
        app: secrets-manager-csi-driver
    spec:
      containers:
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --logtostderr
        - --v=5
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        image: icr.io/ibm/secrets-manager-csi-driver:1.1.0
        imagePullPolicy: Always
        name: secrets-manager-csi-driver
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: false
          runAsUser: 0
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /var/lib/kubelet/pods
          mountPropagation: Bidirectional
          name: mountpoint-dir
        - mountPath: /var/lib/kubelet/plugins
          mountPropagation: Bidirectional
          name: plugins-dir
        - mountPath: /dev
          name: device-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        - --v=5
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/secrets-manager.csi.ibm.io/csi.sock
        image: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.3.0
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /registration/secrets-manager.csi.ibm.io /registration/secrets-manager.csi.ibm.io-reg.sock
        name: node-driver-registrar
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
        - mountPath: /registration
          name: registration-dir
      hostNetwork: true
      serviceAccountName: secrets-manager-csi-driver
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /var/lib/kubelet/plugins/secrets-manager.csi.ibm.io
          type: DirectoryOrCreate
        name: socket-dir
      - hostPath:
          path: /var/lib/kubelet/pods
          type: Directory
        name: mountpoint-dir
      - hostPath:
          path: /var/lib/kubelet/plugins
          type: Directory
        name: plugins-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: Directory
        name: registration-dir
      - hostPath:
          path: /dev
        name: device-dir
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager-csi-driver
  namespace: secrets-manager-csi-driver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-manager-csi-driver
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-manager-csi-driver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secrets-manager-csi-driver
subjects:
- kind: ServiceAccount
  name: secrets-manager-csi-driver
  namespace: secrets-manager-csi-driver
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: secrets-manager.csi.ibm.io
spec:
  attachRequired: false
  podInfoOnMount: true
  volumeLifecycleModes:
  - Ephemeral